# This file shows the example structure of the secrets.  DO NOT USE password as it is.
# Use git-secret to encrypt values-secrets.yaml might be safer.

global:
  postgresql:
    auth:
      postgresPassword: REPLACE_ME
      user: airflow
      password: REPLACE_ME

airflow:
  externalDatabase:
    password: REPLACE_ME

# See: https://github.com/apache/druid/issues/14867
druid:
  configVars:
    druid_metadata_storage_connector_password: druid

kafka:
  secrets:
    name: r-kafka-user-passwords
    username: user1
    password: client-passwords

postgresql:
  primary:
    initdb:
      scripts:
        000000-user.sql: |
          CREATE USER airflow WITH PASSWORD 'REPLACE_ME';
          CREATE USER druid WITH PASSWORD 'druid';
          CREATE USER superset WITH PASSWORD 'REPLACE_ME';

superset:
  configOverrides:
    secret: |
      SECRET_KEY='REPLACE_ME'
  postgresql:
    auth:
      password: REPLACE_ME
