# This file shows the example structure of the secrets.  DO NOT USE password as it is.
# Use git-secret to encrypt values-secrets.yaml might be safer.

global:
  postgresql:
    auth:
      postgresPassword: REPLACE_ME
      user: airflow
      password: REPLACE_ME

airflow:
  externalDatabase:
    password: REPLACE_ME

druid:
  configVars:
    druid_metadata_storage_connector_password: REPLACE_ME

postgresql:
  primary:
    initdb:
      scripts:
        000000-user.sql: |
          CREATE USER airflow WITH PASSWORD 'REPLACE_ME';
          CREATE USER druid WITH PASSWORD 'REPLACE_ME';
          CREATE USER superset WITH PASSWORD 'REPLACE_ME';

superset:
  configOverrides:
    secret: |
      SECRET_KEY='REPLACE_ME'
  postgresql:
    auth:
      password: REPLACE_ME
